[package]
name = 'calculator'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }

[addresses]
metaschool = "0x5ea690dde8edd7fe135290acc2440eaef8b67e830ca618b8230e78c6532e09b2"
std = "0x1"